@echo off
echo Starting ChartYap...
echo Starting Backend...
start cmd /k "cd backend && venv\Scripts\activate && uvicorn main:app --reload"
echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"
echo Done! App should open on localhost:5173
