import React, { useMemo } from 'react';
import { VegaEmbed } from 'react-vega';
import { CheckCircle2, XCircle, HelpCircle, Eye } from 'lucide-react';

interface UserChoiceDisplayProps {
    userImage: string | null;
    recommendations: any[]; // The full list of valid recommendations generated by backend
    data: any[];
    detectedType: string; // Now comes from the real backend analysis
}

const TYPE_LABELS: Record<string, string> = {
    'arc': 'Pie / Donut',
    'bar': 'Bar Chart',
    'line': 'Line Chart',
    'point': 'Scatter Plot',
    'area': 'Area Chart',
    'rect': 'Heatmap',
    'tick': 'Strip Plot',
    'boxplot': 'Boxplot'
};

export const UserChoiceDisplay: React.FC<UserChoiceDisplayProps> = ({ userImage, recommendations, data, detectedType }) => {
    if (!userImage) return null;

    // Logic: See if the backend detected type exists in the recommendations
    const match = useMemo(() => {
        return recommendations.find(r => r.type === detectedType);
    }, [recommendations, detectedType]);

    const displayLabel = TYPE_LABELS[detectedType] || detectedType.toUpperCase();

    return (
        <div className="w-full bg-[var(--swiss-gray)] p-8 mb-12 border border-black animate-fade-in">
            <h2 className="swiss-title text-2xl uppercase mb-6 flex items-center gap-2">
                <span className="bg-black text-white px-2">IMAGE ANALYSIS</span>
                Result
            </h2>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">

                {/* Left: User's Upload */}
                <div className="flex flex-col gap-2">
                    <span className="text-xs font-bold uppercase tracking-widest text-gray-500">Your Reference Visual</span>
                    <div className="border-2 border-dashed border-gray-400 p-2 bg-white relative">
                        <img src={userImage} alt="User Reference" className="w-full h-64 object-contain" />
                        <div className="absolute top-2 right-2 bg-black text-white px-2 py-1 text-xs font-bold uppercase flex items-center gap-1">
                            <Eye size={12} />
                            Detected: {displayLabel}
                        </div>
                    </div>
                </div>

                {/* Right: Validation & Result */}
                <div className="flex flex-col gap-4">
                    <div className="flex items-center gap-3 pb-4 border-b border-gray-300">
                        {match ? (
                            <CheckCircle2 className="text-green-600" size={32} />
                        ) : (
                            <XCircle className="text-[var(--swiss-red)]" size={32} />
                        )}
                        <div>
                            <h3 className="text-lg font-bold uppercase">
                                {match ? "Valid Match" : "Incompatible Data"}
                            </h3>
                            <p className="text-sm text-gray-600">
                                The system identified a <strong className="uppercase">{displayLabel}</strong> from your image.
                                {match ? " This chart type is suitable for your data." : " However, your data columns do not support this chart type."}
                            </p>
                        </div>
                    </div>

                    <div className="bg-white p-4 border border-gray-200 h-64 flex flex-col justify-center relative overflow-hidden">
                        {match ? (
                            <>
                                <p className="text-xs text-gray-500 mb-2 uppercase text-center absolute top-2 left-0 w-full z-10">Generative Output</p>
                                <div className="flex-grow w-full pt-6">
                                    <VegaEmbed
                                        spec={{
                                            $schema: 'https://vega.github.io/schema/vega-lite/v5.json',
                                            data: { values: data },
                                            mark: match.type,
                                            encoding: match.encoding,
                                            width: "container",
                                            height: 200,
                                            autosize: { type: "fit", contains: "padding" },
                                            config: { background: "transparent", view: { stroke: "transparent" } }
                                        }}
                                        options={{ actions: false }}
                                        className="w-full h-full"
                                    />
                                </div>
                            </>
                        ) : (
                            <div className="flex flex-col items-center justify-center text-center h-full text-gray-400 p-6">
                                <HelpCircle size={48} className="mb-3 text-gray-300" />
                                <p className="text-sm font-bold text-gray-700 mb-1">Recommendation</p>
                                <p className="text-xs leading-relaxed max-w-xs mx-auto">
                                    We recommend choosing one of the generated charts below that better fits your dataset's structure.
                                </p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};
